# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"MNIST_NORMALIZATION": "01_dataloader.ipynb",
         "AmbiguousMNIST": "01_dataloader.ipynb",
         "FastMNIST": "01_dataloader.ipynb",
         "DirtyMNIST": "01_dataloader.ipynb"}

modules = ["dirty_mnist.py"]

doc_url = "https://blackhc.github.io/ddu_dirty_mnist/"

git_url = "https://github.com/blackhc/ddu_dirty_mnist/tree/master/"

def custom_doc_links(name): return None
